
// keyword
"if" IF
"else" ELSE
"int" INT
"float" FLOAT
"return" RETURN
"void" VOID
"do" DO
"while" WHILE

// symbol

"\\+" PLUS
"-" MINUS
"\\*" MUL
"/" DIV
"%" MOD
"<" LT
"<=" LTE
"==" EQ
">" GT
">=" GTE
"!=" NE
";" SEM
"=" ASSIGN
"," COM

"\\(" LP
"\\)" RP
"\\[" LSB
"\\]" RSB
"{" OB
"}" CB

// others
"[_a-zA-Z][_a-zA-Z0-9]*" ID
"[0-9]+(.[0-9]+)?" NUMBER

// skip
"[ \t\n]+" skip
"//[ -~]*\n" skip
